config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'homes#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
  end
  resources :news do
  end
  resources :article_stores do
    resources :articles
  end
  resources :book_stores do
    resources :books
  end
  resources :lecture_stores do
    resources :lectures
  end
  resources :rule_stores do
    resources :rules
  end
  resources :photo_stores do
    resources :albums do
      resources :photos
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :photo_store
  has_many :photos, :dependent => :destroy
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :article_store
end

app/models/article_store.rb
class ArticleStore < ActiveRecord::Base
  has_many :articles, :dependent => :destroy
end

app/models/book.rb
class Book < ActiveRecord::Base
 belongs_to :book_store
end

app/models/book_store.rb
class BookStore < ActiveRecord::Base
  has_many :books, :dependent => :destroy
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :lecture_store
end

app/models/lecture_store.rb
class LectureStore < ActiveRecord::Base
  has_many :lectures, :dependent => :destroy
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
end

app/models/photo_store.rb
class PhotoStore < ActiveRecord::Base
  has_many :albums, :dependent => :destroy
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :rule_store
end

app/models/rule_store.rb
class RuleStore < ActiveRecord::Base
  has_many :rules, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save   :downcase_email
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive:false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_blank: true
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/menu/_article.html.erb
<li>
  <a class="top-heading" href="#">
    Luận
  </a>
  <i class="caret"></i>     
  <div class="dropdown">
  <div class="dd-inner">
    <div class="column">
      <h4><u>Luận</u></h4>
      <% @article_stores = ArticleStore.all %>
      <% @article_stores.each do |article_store| %>
        <%= link_to article_store.name, article_store_path(article_store) %>
      <% end %>
      <%= link_to "Create", new_article_store_path %>
      </div>
    </div>
  </div>
</li>

app/views/layouts/menu/_book.html.erb
<li>
  <a class="top-heading" href="#">
    Kinh
  </a>
  <i class="caret"></i>       
  <div class="dropdown">
  <div class="dd-inner">
    <div class="column">
      <h4><u>Kinh</u></h4>
      <% @book_stores = BookStore.all %>
       <% @book_stores.each do |book_store| %>
         <%= link_to book_store.name, book_store_path(book_store) %>
        <% end %>
        <%= link_to "Create", new_book_store_path %>
      </div>
    </div>
  </div>
</li>

app/views/layouts/menu/_lecture.html.erb
<li>
  <a class="top-heading" href="#">
    Bài Giảng
  </a>
  <i class="caret"></i>         
  <div class="dropdown">
  <div class="dd-inner">
    <div class="column">
      <h4><u>Bài Giảng</u></h4>
      <% @lecture_stores = LectureStore.all %>
        <% @lecture_stores.each do |lecture_store| %>
          <%= link_to lecture_store.name, lecture_store_path(lecture_store) %>
        <% end %>
        <%= link_to "Create", new_lecture_store_path %>
      </div>
    </div>
  </div>
</li>

app/views/layouts/menu/_login.html.erb
<% if logged_in? %>
<li><%= link_to "Đăng xuất", logout_path,
                method: "delete", 'data-no-turbolink' => 'true' %>
      </li>
<% else %>
  <li><%= link_to "Đăng nhập", login_path, 'data-no-turbolink' => 'true' %></li>
<% end %>

app/views/layouts/menu/_other.html.erb
<li class="full-width">
  <span class="top-heading">Mục khác</span>
  <i class="caret"></i>           
  <div class="dropdown right-aligned">
    <div class="dd-inner">
      <div class="column">
        <h4>Phật giáo</h4>
          <%= link_to "Phật giáo Việt nam", "#" %>
          <%= link_to "Phật giáo quốc tế", "#" %>
        </div>
        <div class="column">
          <h4>Lời ngỏ </h4>
           <%= link_to "Lời ngỏ", root_path %>
           <%= link_to "Góp ý", root_path %>
        </div>
        <div class="column">
          <h4>Lịch sử </h4>
           <%= link_to "Lịch sử phật giáo Việt nam", root_path %>
           <%= link_to "Lịch sử phật giáo quốc tế", root_path %>
        </div>
        <div class="column">
          <h4>Văn hóa </h4>
           <%= link_to "Nghi lễ", root_path %>
           <%= link_to "Ăn chay", root_path %>
        </div>
        <div class="column">
          <h4>Văn học </h4>
           <%= link_to "Văn học", root_path %>
           <%= link_to "Thơ ca", root_path %>
        </div>
        <div class="column">
          <h4>Nghệ thuật </h4>
           <%= link_to "Nghệ thuật", root_path %>
           <%= link_to "Thư pháp", root_path %>
        </div>
    </div>
  </div>
</li>

app/views/layouts/menu/_photo.html.erb
<li>
  <a class="top-heading" href="#">
    Hình ảnh
  </a>
  <i class="caret"></i>     
  <div class="dropdown">
  <div class="dd-inner">
    <div class="column">
      <h4><u>Hình ảnh</u></h4>
        <% @photo_stores = PhotoStore.all %>
        <% @photo_stores.each do |photo_store| %>
          <%= link_to photo_store.name, photo_store_path(photo_store) %>
        <% end %>
        <%= link_to "Create", new_photo_store_path %>
      </div>
    </div>
  </div>
</li>

app/views/layouts/menu/_rule.html.erb
<li>
  <a class="top-heading" href="#">
    Luật
  </a>
  <i class="caret"></i>     
  <div class="dropdown">
  <div class="dd-inner">
    <div class="column">
      <h4><u>Luật</u></h4>
        <% @rule_stores = RuleStore.all %>
        <% @rule_stores.each do |rule_store| %>
          <%= link_to rule_store.name, rule_store_path(rule_store) %>
        <% end %>
        <%= link_to "Create", new_rule_store_path %>
      </div>
    </div>
  </div>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>