config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'homes#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
  end
  resources :news do
  end
  resources :article_stores do
    resources :articles
  end
  resources :book_stores do
    resources :books
  end
  resources :lecture_stores do
    resources :lectures
  end
  resources :rule_stores do
    resources :rules
  end
  resources :photo_stores do
    resources :albums do
      resources :photos
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :photo_store
  has_many :photos, :dependent => :destroy
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :article_store
end

app/models/article_store.rb
class ArticleStore < ActiveRecord::Base
  has_many :articles, :dependent => :destroy
end

app/models/book.rb
class Book < ActiveRecord::Base
 belongs_to :book_store
end

app/models/book_store.rb
class BookStore < ActiveRecord::Base
  has_many :books, :dependent => :destroy
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :lecture_store
end

app/models/lecture_store.rb
class LectureStore < ActiveRecord::Base
  has_many :lectures, :dependent => :destroy
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
end

app/models/photo_store.rb
class PhotoStore < ActiveRecord::Base
  has_many :albums, :dependent => :destroy
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :rule_store
end

app/models/rule_store.rb
class RuleStore < ActiveRecord::Base
  has_many :rules, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save   :downcase_email
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive:false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_blank: true
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/lecture_stores_controller.rb
class LectureStoresController < ApplicationController
  def index
  end

  def new
    @lecture_store = LectureStore.new
  end

  def create
    @lecture_store = LectureStore.new lecture_store_params
    if @lecture_store.save
      redirect_to root_path
    else
      flash[:danger] = "Create fails, please retry."
      render 'new'
    end
  end

  def show
    @lecture_store = LectureStore.find params[:id]
    @lectures = @lecture_store.lectures
  end

  def edit
    @lecture_store = LectureStore.find params[:id]
  end

  def update
    @lecture_store = LectureStore.find params[:id]
    if @lecture_store.update_attributes lecture_store_params
     redirect_to lecture_store_path(@lecture_store)
    else
      render 'edit'
    end
  end

  def destroy
    @lecture_store = LectureStore.find params[:id]
    @lecture_store.destroy
    redirect_to root_path
  end

  private
  def lecture_store_params
    params.require(:lecture_store).permit(:name, :description)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lecture_helper.rb
module LectureHelper
end

app/helpers/lecture_stores_helper.rb
module LectureStoresHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/lecture_stores/edit.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for @lecture_store, method: :patch do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
                                  placeholder: "Name" %>
    </div>
    <div class="form-group">
      <label>Description</label>
      <%= f.text_field :description, class: "form-control",
                                  placeholder: "Description" %>
    </div>
    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/lecture_stores/new.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for @lecture_store do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
                                  placeholder: "Name" %>
    </div>
    <div class="form-group">
      <label>Description</label>
      <%= f.text_field :description, class: "form-control",
                                  placeholder: "Description" %>
    </div>
    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/lecture_stores/show.html.erb
<h2>Lecture : <%= @lecture_store.name%></h2>
<h4>
  <%= link_to "Add lecture",  new_lecture_store_lecture_path(@lecture_store)%>
</h4>
<h4>
  <%= link_to "Edit",  edit_lecture_store_path(@lecture_store)%>
</h4>
<h4>
  <%= link_to "Delete", lecture_store_path(@lecture_store),
                    method: :delete,
                    data: { confirm: 'Make sure you want to do this?' }%>
</h4>
  
<hr>
<% @lectures.each do |lecture| %>
  <%= link_to lecture.name, lecture_store_lecture_path(@lecture_store, lecture) %>
<% end %>